# Generated by Django 4.2.6 on 2023-10-10 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iotdata',
            old_name='timestamp',
            new_name='datetime',
        ),
    ]
