version: '3'

services:
  runserver:
    build:
      context: .
    volumes:
      - ${PWD}/db.sqlite3:/app/db.sqlite3
    ports:
      - "8000:8000"
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  subscribe_iot_data:
    build:
      context: .
    volumes:
      - ${PWD}/db.sqlite3:/app/db.sqlite3
    command: ["python", "manage.py", "subscribe_iot_data"]
    depends_on:
      - mqtt

  fetch_iotdata:
    build:
      context: .
    volumes:
      - ${PWD}/db.sqlite3:/app/db.sqlite3
    command: ["python", "manage.py", "fetch_iot_data"]
    depends_on:
      - mqtt

  chatbot:
    build:
      context: .
    volumes:
      - ${PWD}/db.sqlite3:/app/db.sqlite3
    ports:
      - "7860:7860"
    command: ["python", "manage.py", "chatbot"]

  mqtt:
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
